version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: postgres_vsa_demo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: VsaDemoAppDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1@2#3$4%
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
